version: "3.9"

services:
  yeeeey-bot-app:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - secret.env
    restart: always
    logging:
      options:
        max-size: "1G"
        max-file: "4"
